# Generated by Django 3.2.6 on 2021-08-15 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_books_app', '0006_auto_20210815_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(blank=True, default='test', to='django_books_app.Author'),
        ),
    ]
