# Generated by Django 3.2.6 on 2021-08-16 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_books_app', '0008_auto_20210816_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(default='Shit title', max_length=50),
            preserve_default=False,
        ),
    ]
