# Generated by Django 3.2.6 on 2021-08-16 16:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('django_books_app', '0009_review_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='add_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
