# Generated by Django 3.2.6 on 2021-08-16 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_books_app', '0011_book_cover_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
