# Generated by Django 3.2.6 on 2021-08-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_books_app', '0013_alter_author_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_img',
            field=models.ImageField(default='images/default_image.jpg', upload_to='images/'),
        ),
    ]
