# Generated by Django 3.2.6 on 2021-08-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_books_app', '0014_alter_book_cover_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_img',
            field=models.ImageField(default='images/default_image.png', upload_to='images/'),
        ),
    ]
