# Generated by Django 3.2.6 on 2021-08-16 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_books_app', '0015_alter_book_cover_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_text',
            field=models.TextField(max_length=1000),
        ),
    ]
