# Generated by Django 3.2.6 on 2021-08-16 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_books_app', '0017_alter_review_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
    ]
