# Generated by Django 3.2.6 on 2021-08-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_books_app', '0025_alter_review_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(default='desc', max_length=2000),
            preserve_default=False,
        ),
    ]
