# Generated by Django 3.2.6 on 2021-08-18 12:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_books_app', '0029_alter_book_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(max_length=2000, validators=[django.core.validators.MinLengthValidator(100)]),
        ),
    ]
