# Generated by Django 3.2.6 on 2021-08-19 09:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_books_app', '0030_alter_book_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_text',
            field=models.TextField(max_length=1000, validators=[django.core.validators.MinLengthValidator(200)]),
        ),
    ]
