# Generated by Django 3.2.6 on 2021-08-19 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_books_app', '0034_book_cover_img_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='cover_img_url',
        ),
    ]
