# Generated by Django 3.2.6 on 2021-08-21 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_books_app', '0037_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
